### PR TITLE
Update jsonwebtoken crate to latest version

### PR DESCRIPTION
**Pull request by vishrutss**
Resolves https://github.com/ndelvalle/rustapi/issues/459

### CODE REVIEW

**Comment by ndelvalle** [comment]
No breaking changes? Nice! @vishrutss sorry I just merged a PR that updated the Cargo.lock so you now have conflicts, can you pull my latests changes and update the PR?

**Comment by vishrutss** [comment]
Oh my bad. Didn't see that. I'll update it.

**Comment by vishrutss** [comment]
Hey @ndelvalle. The merge conflicts in the lock file are getting a bit confusing and I don't want to make any breaking changes. Is it ok if I just create a new PR after pulling the latest changes?

**Comment by ndelvalle** [comment]
> @ndelvalle I have raised a separate PR #465. Is it ok if I close this PR?

Yep I am closing this one, thanks!

**Pull request closed without merging**
